### ISSUE TITLE
Add GSAP as part of the dependencies

### ISSUE THREAD

**Issue by pigeonfresh** [riccomediamonks/muban-transition-component#4]
MTC relies on GSAP to work. In most cases GSAP is already part of the project. So, should we add GSAP as a dependency?

**Comment by ThaNarie** [comment]
Best to have such libraries as peerDeps (and as devDep for development). Not as a normal dep, otherwise it's hard to manage different gsap versions that are used by different libs and try to bundle their own version (resulting in a larger project bundle).

**Comment by riccoarntz** [comment]
added gsap as peerDep
